services:
  backend:
    build: ./backend
    container_name: vpn-backend
    restart: always
    env_file: ./backend/.env
    expose:
      - "3001"
    networks:
      - marzx-net
      - site-net

  frontend:
    build: ./frontend
    container_name: vpn-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - site-net

networks:
  marzx-net:
    external: true
  site-net:
    driver: bridge
